dist: focal
language: python
jobs:
  include:
    - python: "3.7"
      env: RUN_PRE_COMMIT=0
    - python: "3.8"
      env: RUN_PRE_COMMIT=0
    - python: "3.9"
      env: RUN_PRE_COMMIT=1
    - python: "3.10"
      env: RUN_PRE_COMMIT=0
install:
- pip install -U setuptools pip -r build-requirements.txt
script:
- if [[ $RUN_PRE_COMMIT = 1 ]]; then
    pip install -U pre-commit==2.20.0 &&
    pre-commit install &&
    pre-commit run --all;
  fi
- python setup.py bdist_wheel && pip install dist/anybadge*.whl
- (mkdir tmp && cd tmp && pytest --doctest-modules --cov=anybadge --cov-report html:htmlcov ../anybadge ../tests)
before_deploy:
- sed -i "s/^version = .*/version = __version__ = \"$TRAVIS_TAG\"/" anybadge/__init__.py
deploy:
- provider: pypi
  skip_cleanup: true
  username: "__token__"
  password:
    secure: "Sr70Dc1uEmVmYIupa0FApydxX0TBmXp9xyD9DX+CEeQfJV2cluw+wluMHHwyzjSdDk2qU40R/qc4AFPNGf+ticaq5zHrTDHF68EVMSzKxr7j+2OW3C6PXxcPMImaGRScL/263TVsY2cdAQ+rzYWnONSgVbgeSJth2/TuQJcD53Q8pra7KDgskoC0mnhcWY0Ss2wv9mIyRpjPcsR68YkENPTVORwzek761R3glTxdGmDOW7ac74p70XC8X75RKwfJMAL9xfibWX4b2jaodBFs/lfj+beBI1RVPYb/33am1HLMKupEP/OJ+UNHg2zaiX2xmrX/30qCsug9x50hgDmJvxcaXyh+gJ0v2RuILTSlpxI7XhOuzMzNFtd2kMiI4DT5/3WYNAlUTFZuxlh50CT7cNRgz8+jT1hwUuQu9fJRI1o5kQV4gyTI569ec3Uj+NJ1SHMDfTYjpGnF9D1RQzRKS1gAv+fxumzb6HBPM+Pb0agdJ/H4bDlcXYxBGu0CUW1EbEwgxyU9W/q6eSTObtrFLnl2QLABK4L5JeE6DdcyBOH2AJOZHELAzKUNRLpIaIIG657VJjZBM6HKRLpDiHY6vcd0ehONCaBtI4nr22Pr5WuIUEP5R4w57wNc6ytW4LJurajT/yXW5l4HRTiKdO6ZkKQl+FPRQh4NUzK0ZXXvJ/g="
  distributions: sdist bdist_wheel
  on:
    tags: true
    all_branches: true
    python: '3.9'
